pip install cgitb
pip install os
pip install re
pip install json
pip install ipaddress
pip install discord_webhook
pip install Request
pip install urlopen
pip install pystyle
pip install time